version: '3'
services:
  zk:
    image: 'zookeeper:3.4'
    networks:
      - docker-mesos
    ports:
      - 2181:2181
  mesos-master:
    build:
      context: 'mesos-master'
      args:
        MESOS_VERSION: 1.4.0-2.0.1
    command: mesos-master --registry=in_memory --port=5050 --zk=zk://zk:2181/mesos --log_dir=/var/log/mesos
    networks:
      - docker-mesos
    ports:
      - 5050:5050
    expose:
      - 5050
    depends_on:
      - zk
  mesos-slave:
    build:
      context: 'mesos-slave'
      args:
        MESOS_VERSION: 1.4.0-2.0.1
    command: mesos-slave --port=5051 --master=zk://zk:2181/mesos --work_dir=/sandbox --log_dir=/var/log/mesos --hostname=localhost --isolation=filesystem/linux,docker/runtime --image_providers=docker
    privileged: true
    networks:
      - docker-mesos
    depends_on:
      - mesos-master
    ports:
      - 5051:5051
    expose:
      - 5051
    volumes:
      - ./tmp/sandbox:/sandbox
    depends_on:
      - mesos-master
  marathon:
    build:
      context: 'marathon'
      args:
        MARATHON_VERSION: 1.5.1
    command: --master zk://zk:2181/mesos --zk zk://zk:2181/marathon
    networks:
      - docker-mesos
    depends_on:
      - mesos-master
    ports:
      - 8080:8080
    expose:
      - 8080
networks:
  docker-mesos:
